### ISSUE TITLE
XLA OOM Error when running notebook

### ISSUE THREAD

**Issue by alembcke** [google-research/perceiver-ar#14]
When running the `inference.ipynb` notebook locally I get the below error on the cell titled "Sample the sequence".  I think this might be related to this [JAX note](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html).

```
---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
Input In [10], in <cell line: 24>()
     21 tick = time.time()
     22 print('starting generation', tick)
---> 24 outputs = sample_sequences(
     25     events, rng, start_step, num_steps, temperature, top_p)
     27 outputs = jax.tree_map(lambda x: x.block_until_ready(), outputs)
     28 tock = time.time()

    [... skipping hidden 9 frame]

File ~/.local/lib/python3.10/site-packages/jax/interpreters/pxla.py:1742, in ExecuteReplicated.__call__(self, *args)
   1740       dispatch.runtime_tokens.set_output_token(device, token)
   1741 else:
-> 1742   out_bufs = self.xla_executable.execute_sharded_on_local_devices(
   1743       input_bufs)
   1744 if dispatch.needs_check_special():
   1745   for bufs in out_bufs:

XlaRuntimeError: INTERNAL: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```

I noticed that the cell titled "Memory parameters" has the line:

```py
use_memory = True #@param {type:"boolean"}
```

I changed this to `False`, which changed the error output a little, but it was still the same OOM error.  I also tried different options in the earlier mentioned [JAX note](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html), but nothing solved the issue.

Platform info:
OS: Ubuntu 22.04
GPU: RTX 3080 w/ 16GB VRAM
PC RAM: 32GB

**Comment by alembcke** [comment]
Sorry, I am not used to working with environment variables, I needed to put the entire line below at the end of the first code cell (basically, after JAX is imported, but before any calls to JAX):

```py
%env XLA_PYTHON_CLIENT_PREALLOCATE=false
```

That solved my issue.

Not sure if it helps, but I also have an integrated Intel GPU, so I changed `prime-select = on-demand` - so that could help as well.  Closing the issue as this is solved.

**Comment by alembcke** [comment]
I had a similar issue when running the command:

```
PYTHONPATH=.::$PYTHONPATH python perceiver_ar/experiment.py \
  --config=perceiver_ar/experiment.py:random_mirrored_32
```

The solution was to add the lines below to `perceiver_ar/experiment.py`:

```py
# Tell JAX not to hog the GPU VRAM
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'
# Tell TensorFlow not to hog the GPU VRAM
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    tf.config.experimental.set_virtual_device_configuration(
        gpus[0],[tf.config.experimental.VirtualDeviceConfiguration(memory_limit=5120)])
  except RuntimeError as e:                                                                                                                                                                                      
    print(e
```

The first part was is equivalent to `%env XLA_PYTHON_CLIENT_PREALLOCATE=false` in the Juptyer notebook, while the second part is taken from this [StackOverflow answer](https://stackoverflow.com/questions/69401285/attempting-to-perform-blas-operation-using-streamexecutor-without-blas-support).  It seems that both JAX and TensorFlow are being used, so both need to be told to share the GPU VRAM.

I am reopening this issue as I wonder, is there a way to test if the this issue and the previous one in the original post can be fixed by testing if these lines are necessary, and if they are, having them executed automatically?

**Comment by cghawthorne** [comment]
Hmm, I suspect the issue is Tensorflow trying to use the GPU during the data pipeline. Can we just add this line to `experiment.py`?

```
tf.config.set_visible_devices([], "GPU")
```
